
spring:
  redis:
    timeout: 2000
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
        max-wait: 200
        shutdown-timeout: 8

